version: '3'
 
services:
  netatalk:
    image: servercontainers/netatalk
    restart: always
    network_mode: host
    environment:
      NETATALK_GLOBAL_CONFIG_1: 'mimic model = TimeCapsule'

      ACCOUNT_alice: alipass
      ACCOUNT_bob: bobpass

      NETATALK_VOLUME_CONFIG_aliceonly: "[Alice Share]; path=/shares/alice; valid users = alice"
      NETATALK_VOLUME_CONFIG_bobstm: "[TimeCapsule]; path=/shares/timemachine; valid users = bob; vol size limit = 100000; time machine = yes"
    volumes:
      - ./shares/alice:/shares/alice
      - ./shares/timemachine:/shares/timemachine
